rm(list=ls())
setwd("E:/particle垂直分布/傅里叶离子回旋共振质谱/analysis/质谱图")
library("MALDIquant")
library("MALDIquantForeign")
s <- import(path="E:/particle垂直分布/傅里叶离子回旋共振质谱/analysis/质谱图",type="csv")
any(sapply(s,isEmpty))
table(sapply(s,length))
all(sapply(s,isRegular))
plot(s[[11]])
